// sub-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'sub-angular';
}

// base/src/App.tsx
import './App.css';
import { Link } from 'react-router-dom';

function App() {
    return (
        <>
            <div>
                <span>主应用</span>
                <br />
                <Link to="/sub-react">sub-react</Link>
                <br />
                <Link to="/sub-vue">sub-vue</Link>
                <br />
                <Link to="/sub-angular">sub-angular</Link>
            </div>

            <div id="sub-app"></div>
        </>
    );
}

export default App;
